- example/example.conf
- src/enftun.c
- src/options.c
- src/options.h
- src/tls.c
- src/tls.h
This mark can be used by the host routing policy to ensure that tunnel
packets are not routed back into the tunnel.
Fixes #12
> tls: set mark on outgoing packets

- CMakeLists.txt
- src/context.c
- src/context.h
- src/enftun.c
Keep the context struct and methods separate from the main program
loop.
> context: refactor into separate file

- tools/enftun-setup
The Linux kernel handles IPv6 multicast routing via the `local` table instead of `main`, so adjust our default and prefix-specific commands to handle this.
> Fix multicast routing

- example/example.conf
- src/config.c
- src/config.h
- src/enftun.c
- src/tls.c
- src/tls.h
The enftun should not use DNS to lookup the remote host, but instead simply connect to a specific IP. To support both IPv4 and IPv6 networks (and some forms of high-availability), the client must be able to specific multiple IP addresses for the enftun to use.
This commit changes the `remote.host` parameter to a list `remote.hosts`.  Each of these hosts or IPs are attempted in order, until one succeeds or all fail.
Closes #18
> Accept multiple remote hosts or IP addresses

- tools/enftun-setup
1. Added iptables config
2. Added ip6tables config 
add_firewall will configure both so we expect both enf server ipv4 and ipv6 to be in the enftun config otherwise it will break 
Depends on enftun to support `remote.host.ipv4` and `remote.host.ipv6` parameters instead of just `remote.host`
3. No need for iptables delete as they don't survive reboots
4. Added support for ipv6 address in the python test router. (Maybe not the most elegant ipv6 address validation, but it works)
Closes #28
> Add firewall configuration to enftun-setup

- CMakeLists.txt
- cmake/Findsodium.cmake
- example/device.conf
- example/server.conf
- src/config.c
- src/config.h
- src/enftun.c
- src/tls.c
- src/tls.h
- src/xtt.c
- src/xtt.h
- test/test.conf
`xtt` is run in order to generate a certificate and key for the `enftun` to use, rather than passing in ready-made certificates and keys. This also allows us to specify whether we want to use `xtt` to generate credentials or simply run TLS. 
Fixes #1
> Add XTT support 

- src/config.c
- src/config.h
- src/enftun.c
- src/xtt.c
- src/xtt.h
In order for the customer and management traffic to have their own enftun connections, and be in different DAA groups, we need the ability to change the basename. Now, we can do so by setting the basename in the config file.
> Ability to change DAA basename 

- CMakeLists.txt
- README.md
- src/xtt.c
- src/xtt.h
These changes will be necessary when XTT cuts a new release since the server_id and expiry have been taken out, and the NVRAM handles and functions for initializing the sapi and tcti contexts have been added to the XTT library. 
This fixes #44 because the xaptum-tpm updates will allow us to read variable length data from NVRAM.
> Update to accommodate for new XTT changes

- CMakeLists.txt
- src/enftun.c
- src/tcp.c
- src/tcp.h
- src/tls.c
- src/tls.h
- src/xtt.c
- src/xtt.h
This series extracts the TCP connection code from the TLS module into a common module, to be reused by the XTT code.   By using the code, the XTT code will now:
- handle remote hosts specified as a URL, rather than an IP
- accept a list of remote hosts, trying them in order until one succeeds. This important when providing both IPv4 and IPv6 addresses for the remote host.
> Refactor out tcp socket handling

- src/tcp.c
Trying to add continuous integration, we found that dev builds would fail because of uninitialized variables.
> tcp: intialize variable

- src/tun.c
In `tun.c`, `linux/ipv6.h` includes `linux/in6.h` which conflicts with the `netinet/in.h` included by `ip.h` so we changed both of the conflicting files to their `net/` or `netinet/` counterparts.
> Use net or netinet includes over linux

- src/channel.c
- src/channel.h
- src/tls.c
- src/tls.h
- src/tun.c
- test/router.py
This series fixes a bug where a packet received on the TLS connection was not delivered to the TUN device until a subsequent packet was received.
> read full packet from TLS socket immediately

- src/log.h
The log macros should be expressions, not statements.
> Remove semicolons from log macros

- src/config.c
- src/config.h
- src/context.c
- src/context.h
- src/enftun.c
This series adds the option to write the IP address to a config-specified file.
This is helpful on the router card. Other services like Mender and captived use this address as an identifier for the card.  Exporting to a file makes it easily consumable.
> Add option to export IP address to file

- .docker/Makefile
- .travis.yml
- CMakeLists.txt
- src/xtt.c
Update `enftun` to use `xtt` v0.10.4, so that we have explicitly set permissions for the files that xtt creates (longterm certificate and private key). The docker image was also moved from the `xaptum` repo to `xaptumeng`.
Fixes #66
> Add permissions for xtt created files

- src/ndp.c
It was observed that enftun would hang when stopping the libuv
event loop, if the tun device link state was down when enftun started.
This hang prevented the automatic reconnect when the connection to the ENF
was lost.
The was due to the NDP code failing to cancel the CRB used to write
the router advertisment (RA) to the tun device. When the tun device is
up, the RA is written immediately.  There is no outstanding CRB when
stopping and thus no hang. When the tun device is down, the CRB is
queued.  Whening stopping, there is still an outstanding CRB and the
event loop does not exit.
The fix is to explicitly cancel the RA CRB when stopping, if one is
outstanding.
The chain code is the only other place that CRBs are submitted. Those
already properly canceled outstanding CRBs when stopping. …
> ndp: cancel outstanding crb when stopping

- src/icmp.c
- src/icmp.h
- src/ndp.c
Currently enftun advertises routes using route information options in the main RA. Support for these options can be disabled at compile time in the Linux kernel. This is true for some IoT gateways like the Eurotech RG-20-25.
The original RA specification did include support for advertising the default route via the default lifetime parameter. We currently set this to 0 to disable, and advertised the default route (if configured) via the aforementioned option.
To support both current and legacy systems, we should change how the default route is advertised.
Also, fix an issue with the route info lifetimes being specified in milliseconds instead of seconds. Change those lifetimes to infinite, which is best for our use case.
Fixes #76
> Use router lifetime to advertise default route

- src/dhcp_msgs.c
Some older DHCPv6 clients, specifically connman v1.32 and older, so
not properly support the "infinite" lifetime value 0xFFFFFFFF.
Older version of connman have a second bug. They improperly interpret
the lifetime as a signed integer, so 0xFFFFFFFF becomes -1.  Addresses
are considered expired before they were even assigned.
To workaround this, we specify a finite lifetime.  Because connman
does not properly handle signed vs unsigned ints and the associated
overflow issues, we can't use a large lifetime like 0x7FFFFFFF.  The
lifetime is added to the current time (seconds since the Unix epoch),
which overflows.  So use a relatively short time, 1 year, that won't
overflow.
> dchp6: use finite address lifetimes

- src/conn_state.c
- src/context.c
- src/enftun.c
- src/tcp.c
- src/tcp.h
- src/tls.c
- src/tls.h
- src/xtt.c
Change the way that enftun_tcp is formatted for future additions.
This adds `enftun_tcp_native`  which includes an `enftun_tcp` struct. That struct holds the original file descriptor, local address, and remote address and also a struct (`enftun_tcp_ops`) that holds the 3 necessary functions `connect`, `connect_any`, and `close`.
> Refactor TCP structs

- CMakeLists.txt
- README.md
- src/enftun.c
- src/tcp_psock.c
- src/tcp_psock.h
- src/tls.c
- src/tls.h
- src/xtt.c
Add an option for `enftun` to build with support for psock, or tcp via proxy. 
Using the cmake option `-DBUILD_PSOCK` a user can decide whether to use the psock implementation or the normal tcp enftun.
An attempt at supporting both simultaneously was made, but because `conn_state` is not supported by psock, it is proving more difficult.
Connected to Issue #73.
> Support tcp and tcp proxy

- src/channel.c
- src/packet.c
Moved to accomodate writing to a TLS tunnel without having to manually add the 2 byte buffer every time.
> Reserve 2 bytes for stream header in packet reset

- src/tcp.c
- src/tcp.h
- src/tcp_psock.c
- src/xtt.c
The refactoring to add PSOCK support introduced a bug into the XTT provisioning code that manifested as a SEGFAULT.  
Consider a structure and function:
```
struct foo;
do_with_foo(void*);
Code of the form
```
struct foo f;
do_with_foo(&f);
```
was changed to
```
struct foo* f;
do_with_foo(&f);  // f is now already a pointer, so should be changed to do_with_foo(f)
```
Unfortunately, due to the `void*` argument, the type checker did not catch this mistake.
This PR both
1) removes the extra `&` operator
2) change the signature of `do_with_foo(void*)` to `doo_with_foo(struct foo*)` to avoid similar problems in the future.
> Fix xtt socket handling

- src/context.c
The ipv6 string was not zeroed before re-reading the certificate
file. If the cert changed such that the new ipv6 string was shorter
(for example, if a run of zeros was replaced with a ::), then the ipv6
string buffer would contain the concatentation of the new address and
the remainder of the old address. Obviously, this is invalid and
incorrect.
Prevent this errror by zeroing the ipv6 string buffer before reading
the certificate file.
> context: zero out the ipv6 string buffer before reading cert

- tools/enftun-setup
In some kernels, the `ip tuntap add mode tun` and `ip link set dev
tun0 up` comamnds returns before the effect is complete. Consequently,
subsequent commands in the script can fail.
Fix this by explicitly waiting for the interface to appear (or up)
before continuing.
> enftun-setup: wait for ip commands to succeed

- CMakeLists.txt
- src/conn_state.c
- src/enftun.c
- src/tcp.c
- src/tcp.h
- src/tcp_multi.c
- src/tcp_multi.h
- src/tcp_scm.c
- src/tls.c
- src/tls.h
- src/xtt.c
Not ready to merge. Right now this connects to whichever one is first available (SCM, if enabled, is almost always the first) and stays there. Works both over SCM and WiFi if I disable the host driver. The local def will be superseded by  the toolchain changed we discussed. Will probably also have conn state issues over WiFi when SCM is enabled at compile time.
> Parallel scm

- CMakeLists.txt
- cmake/FindLibConfig.cmake
- cmake/Findsodium.cmake
- src/tls.c
Some IoT gateways and other embedded products have OpenSSL 1.0.x, not the OpenSSL 1.1.x required by enftun.  Upgrading the version of OpenSSL on these platforms is non-trivial, if even possible. So to support them, its easier to adapt enftun to the older version of OpenSSL.
Our usage of the new APIs in 1.1.x is limited to convenience methods for restricting the allowed version of TLS to 1.2.  This same behavior can be enforced on older versions with slightly more verbose code.
> Support openssl 1.0.x

- src/tls.c
This commit fixes our handling of the `SSL_set_min_proto_version` return value to properly detect error responses.
All other uses of OpenSSL functions were audited as well and all appeared to correctly interpret the return value.
> Fix openssl error checking

- .travis.yml
- src/packet.c
- src/tcp.c
- src/tls.c
- src/xtt.c
The various header processing code (ip.c, icmp.c, ndp.c, etc.) require
that the packet be word aligned. Otherwise, it will generate unaligned
memory access traps on some older ARM architectures.
The TLS stream header length is 2 bytes, causing some accesses to be
unaligned.  Fix this by using reserve enough bytes in the header to
ensure that the TLS stream header is half-word aligned and the packet
payload is word aligned.
Fixes #114
> packet: ensure that packet is word aligned

- keygen/src/main.c
Fixes #118 
This error presents in Valgrind as the following
```
==2089== Invalid write of size 1
==2089==    at 0x4C2EE98: strcpy (vg_replace_strmem.c:506)
==2089==    by 0x10ADD0: parse_args (in /home/dev/code/enftun/keygen/enftun-keygen)
==2089==    by 0x10B27D: main (in /home/dev/code/enftun/keygen/enftun-keygen)
==2089==  Address 0xab2de58 is 0 bytes after a block of size 8 alloc'd
==2089==    at 0x4C2BBAF: malloc (vg_replace_malloc.c:299)
==2089==    by 0x10ADB0: parse_args (in /home/dev/code/enftun/keygen/enftun-keygen)
==2089==    by 0x10B27D: main (in /home/dev/code/enftun/keygen/enftun-keygen)
==2089== 
==2089== Invalid write of size 1
==2089==    at 0x4C2EEA7: strcpy (vg_replace_strmem.c:506)
==2089==    by 0x10ADD0: parse_args (in /home/dev/code/enftun/keygen/enftun-keygen) …
```
> Fix allocation error with default enftun_path

- CMakeLists.txt
- README.md
- src/tcp.h
- src/tcp_hss.c
- src/tcp_hss.h
- src/tcp_multi.c
- src/tcp_multi.h
Let me manually confirm this again on the board tonight before merging, but this should be all the changed required for the HSS rename, then the buildroot changes should be easy to apply.
> Rename SCM to HSS

- keygen/src/main.c
- src/xtt.c
This PR fixes an oversight made in the recent PR adding TPM support for the XTT longterm key and keygen utility.
If `tpm_password` is `NULL`, the unconditional calls to `strlen` will segfault. This fixes that by only using `strlen` if `tpm_password` is non-`NULL`.
> tpm: Fix tpm_password strlen call.

- CMakeLists.txt
- src/options.c
- src/version.h.in
Fixes #130 
This PR adds a `-v` option to `enftun` that displays the version number.  ` CMakeLists.txt` is already the source of truth for the version number.  To get this into the C code, a new `version.h.in` header template is introduced.
This request came from a Lanner engineer writing the SOP for integrating `enftun` into their hardware. Apparently their SOPs require a way to confirm the installed version.
I did not update `enftun-keygen` to display a version number.  That should be done eventually, but will require some broader refactoring first:
- share the version number from the main project (keygen is currently stuck at 0.0.1)
- rework the argv parsing to support "command" options like version and help.
clang-format was complaining about some other files, so the second commit …
> Add CLI option to display version number

- example/device.conf
- example/server.conf
- src/config.c
- src/config.h
- src/enftun.c
- src/filter.c
- src/filter.h
- src/ip.h
- test/router.py
- test/test.conf
This series introduces a new config option `route.allow_ipv4`. If set to `true` (default is `false`), IPv4 packets are allowed through the tunnel.  Unlike the IPv6 src/dst address checks, no validations are performed on the IPv4 packets.
No explicit IPv4 support is added to the `enftun-setup` script.   The user must arrange to set an IPv4 address on the interface and configure routing appropriately.
Resolves #132
> Allow IPv4 traffic through tunnel

- CMakeLists.txt
- README.md
- src/xtt.c
The xtt project was recently updated to fix a bug with its certificate generation (cf. [xtt#124](https://github.com/xaptum/xtt/pull/124)). That change altered the public API.
This PR updates this project's usage of xtt to work with the new API (and bumps the version requirement for xtt)
> xtt: Update to new XTT API for certificates.

- keygen/src/main.c
> keygen: handle error in parsing config file

- src/log.c
- src/tls.c
- Fix the `enftun_log_ssl_XXX` macros to properly handle variable arg lists.
- Clear the OpenSSL error queue before new method calls so the correct error is retrieved afterward.
Fixes #125.
> Fix logging of TLS errors
